version: "3.7"

services:
  app:
    build:
      args:
        user: maythegonzalez
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: maythegonzalez
    container_name: maythegonzalez-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
      - ./docker-compose/php/project.ini:/usr/local/etc/php/conf.d/project.ini
    networks:
      - maythegonzalez

  db:
    image: mariadb:10.7
    container_name: maythegonzalez-db
    restart: unless-stopped
    ports:
      - 33306:3306
    environment:
      MARIADB_DATABASE: maythegonzalez
      MARIADB_ROOT_PASSWORD: $X9^j53s
      MARIADB_PASSWORD: $X9^j53s
      MARIADB_USER: maythegonzalez
    volumes:
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/persistent:/var/lib/mysql
    networks:
      - maythegonzalez

  nginx:
    image: nginx:1.21-alpine
    container_name: maythegonzalez-nginx
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./app:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
        - maythegonzalez

networks:
  maythegonzalez:
    driver: bridge
